# Blog settings
permalink: angelofallars.github.io


# My variables
name: Angelo Fallaria | Machine Learning Student
description: Software developer in Python and C studying Data Science / Machine Learning
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
